scoreboard objectives add class_primary dummy "Class Primary"
scoreboard objectives add class_request dummy "Class Request"
scoreboard objectives add class_confirmed dummy "Class Confirmed"
scoreboard objectives add subclass_primary dummy "Subclass Primary"
scoreboard objectives add subclass_request dummy "Subclass Request"
scoreboard objectives add subclass_confirmed dummy "Subclass Confirmed"
scoreboard objectives add fx_color dummy "FX Color"
scoreboard objectives add ability_toggle_1 dummy "Ability Toggle 1"
scoreboard objectives add ability_toggle_2 dummy "Ability Toggle 2"
scoreboard objectives add ability_toggle_3 dummy "Ability Toggle 3"
scoreboard objectives add ability_toggle_4 dummy "Ability Toggle 4"
scoreboard objectives add ability_toggle_5 dummy "Ability Toggle 5"
scoreboard objectives add xp_total dummy "XP Total"
scoreboard objectives add xp_spent dummy "XP Spent"
scoreboard objectives add xp_available dummy "XP Available"
scoreboard objectives add xp_tree_state dummy "XP Tree State"
scoreboard objectives add morph_state dummy "Morph State"
scoreboard objectives add morph_request dummy "Morph Request"
scoreboard objectives add plasma dummy "Plasma"
scoreboard objectives add plasma_max dummy "Plasma Max"
scoreboard objectives add plasma_drain dummy "Plasma Drain"
scoreboard objectives add cd_class dummy "Class Cooldown"
scoreboard objectives add cd_ability_1 dummy "Cooldown Ability 1"
scoreboard objectives add cd_ability_2 dummy "Cooldown Ability 2"
scoreboard objectives add cd_ability_3 dummy "Cooldown Ability 3"
scoreboard objectives add cd_ability_4 dummy "Cooldown Ability 4"
scoreboard objectives add cd_ability_5 dummy "Cooldown Ability 5"
scoreboard objectives add cd_morph dummy "Morph Cooldown"
scoreboard objectives add water_exit dummy "Water Exit"
scoreboard objectives add lycan_vitality dummy "Lycan Vitality"
scoreboard objectives add ww_bonus_hp dummy "Werewolf Bonus Hearts"
scoreboard objectives add morph_bonus dummy "Morph Bonus"
scoreboard objectives add skill_vampire_bite dummy "Baseline Vampire Fangs"
scoreboard objectives add skill_blood_thirst dummy "Skill Blood Thirst"
scoreboard objectives add skill_midnight_strength dummy "Skill Midnight Strength"
scoreboard objectives add skill_bat_morph dummy "Skill Bat Morph"
scoreboard objectives add skill_summon_vampire_troops dummy "Skill Vampire Troops"
scoreboard objectives add skill_vampire_compel dummy "Skill Vampire Compel"
scoreboard objectives add skill_wolf_bite dummy "Baseline Werewolf Fangs"
scoreboard objectives add skill_werewolf_roar dummy "Skill Werewolf Roar"
scoreboard objectives add skill_shadow_wolf_morph dummy "Skill Shadow Wolf Morph"
scoreboard objectives add skill_werewolf_scent dummy "Skill Werewolf Scent"
scoreboard objectives add skill_banshee_invisibility dummy "Skill Banshee Invisibility"
scoreboard objectives add skill_sonic_scream dummy "Skill Sonic Scream"
scoreboard objectives add skill_banshee_phase dummy "Skill Banshee Phase"
scoreboard objectives add skill_banshee_morph dummy "Skill Banshee Morph"
scoreboard objectives add banshee_mind_fracture dummy "Banshee Mind Fracture"
scoreboard objectives add banshee_mind_fracture_enabled dummy "Mind Fracture Toggle"
scoreboard objectives add skill_banshee_soul dummy "Skill Banshee Soul"
scoreboard objectives add banshee_soul_active dummy "Banshee Soul Active"
scoreboard objectives add skill_switch_throw dummy "Skill Switch Throw"
scoreboard objectives add skill_tenacity_charge dummy "Skill Tenacity Charge"
scoreboard objectives add skill_third_hit_double dummy "Skill Third Hit Double"
scoreboard objectives add skill_ninja_agility dummy "Skill Ninja Agility"
scoreboard objectives add skill_multi_jump dummy "Skill Multi Jump"
scoreboard objectives add skill_dagger_throw dummy "Skill Dagger Throw"
scoreboard objectives add skill_strikethrough dummy "Skill Strikethrough"
scoreboard objectives add skill_smoke_bomb dummy "Skill Smoke Bomb"
scoreboard objectives add skill_spell_mastery dummy "Skill Spell Mastery"
scoreboard objectives add skill_necromancy dummy "Skill Necromancy"
scoreboard objectives add skill_staff_mastery dummy "Skill Staff Mastery"
scoreboard objectives add skill_chain_lightning dummy "Skill Chain Lightning"
scoreboard objectives add skill_crit_focus dummy "Skill Crit Focus"
scoreboard objectives add skill_levitate dummy "Skill Levitate"
scoreboard objectives add skill_knockback_boost dummy "Legacy Knockback Boost"
scoreboard objectives add skill_explosive_arrows dummy "Skill Explosive Arrows"
scoreboard objectives add skill_shield_slam dummy "Skill Shield Slam"
scoreboard objectives add skill_fortify dummy "Skill Fortify"
scoreboard objectives add skill_taunt dummy "Skill Taunt"
scoreboard objectives add skill_public_vitality dummy "Skill Public Vitality"
scoreboard objectives add skill_public_haste dummy "Skill Public Haste"
scoreboard objectives add skill_public_parkours dummy "Skill Public Parkourist"
scoreboard objectives add skill_public_second_life dummy "Skill Public Second Life"
scoreboard objectives add skill_public_adrenaline dummy "Skill Public Adrenaline"
scoreboard objectives add skill_public_hp_regen dummy "Skill Public HP Regen"
scoreboard objectives add skill_public_xp_boost dummy "Skill Public XP Boost"
scoreboard objectives add skill_public_luck dummy "Skill Public Luck"
scoreboard objectives add parkourist_active dummy "Parkourist Active"
scoreboard objectives add adrenaline_active dummy "Adrenaline Active"
scoreboard objectives add midnight_strength_active dummy "Midnight Strength Active"
scoreboard objectives add werewolf_scent_active dummy "Werewolf Scent Active"
scoreboard objectives add scent_toggle_state dummy "Scent Toggle"
scoreboard objectives add scent_toggle_initialized dummy "Scent Toggle Ready"
scoreboard objectives add banshee_phase_active dummy "Banshee Phase Active"
scoreboard objectives add fall_immunity_active dummy "Fall Immunity Active"
scoreboard objectives add public_parkourist_enabled dummy "Parkourist Toggle"
scoreboard objectives add public_hp_regen_enabled dummy "HP Regen Toggle"
scoreboard objectives add public_xp_boost_enabled dummy "XP Boost Toggle"
scoreboard objectives add public_skill_toggles_ready dummy "Public Toggles Ready"
scoreboard objectives add skill_toggles_ready dummy "Skill Toggles Ready"
scoreboard objectives add second_life_cd dummy "Second Life Cooldown"
scoreboard objectives add skill_vampire_bite_enabled dummy "Vampire Fangs Toggle"
scoreboard objectives add skill_midnight_strength_enabled dummy "Midnight Strength Toggle"
scoreboard objectives add skill_summon_vampire_troops_enabled dummy "Vampire Troops Toggle"
scoreboard objectives add skill_vampire_compel_enabled dummy "Compel Toggle"
scoreboard objectives add skill_wolf_bite_enabled dummy "Werewolf Fangs Toggle"
scoreboard objectives add skill_werewolf_roar_enabled dummy "Roar Toggle"
scoreboard objectives add lycan_vitality_enabled dummy "Lycan Vitality Toggle"
scoreboard objectives add skill_sonic_scream_enabled dummy "Sonic Scream Toggle"
scoreboard objectives add skill_banshee_invisibility_enabled dummy "Banshee Invisibility Toggle"
scoreboard objectives add skill_banshee_phase_enabled dummy "Banshee Phase Toggle"
scoreboard objectives add skill_banshee_soul_enabled dummy "Banshee Soul Toggle"
scoreboard objectives add skill_switch_throw_enabled dummy "Switch Throw Toggle"
scoreboard objectives add skill_tenacity_charge_enabled dummy "Tenacity Charge Toggle"
scoreboard objectives add skill_third_hit_double_enabled dummy "Third Hit Toggle"
scoreboard objectives add skill_ninja_agility_enabled dummy "Ninja Agility Toggle"
scoreboard objectives add skill_multi_jump_enabled dummy "Multi-Jump Toggle"
scoreboard objectives add skill_dagger_throw_enabled dummy "Dagger Throw Toggle"
scoreboard objectives add skill_strikethrough_enabled dummy "Strikethrough Toggle"
scoreboard objectives add skill_smoke_bomb_enabled dummy "Smoke Bomb Toggle"
scoreboard objectives add skill_necromancy_enabled dummy "Necromancy Toggle"
scoreboard objectives add skill_chain_lightning_enabled dummy "Chain Lightning Toggle"
scoreboard objectives add skill_crit_focus_enabled dummy "Crit Focus Toggle"
scoreboard objectives add skill_levitate_enabled dummy "Levitate Toggle"
scoreboard objectives add skill_shield_slam_enabled dummy "Shield Slam Toggle"
scoreboard objectives add skill_fortify_enabled dummy "Fortify Toggle"
scoreboard objectives add skill_taunt_enabled dummy "Taunt Toggle"
scoreboard objectives add skill_public_luck_enabled dummy "Luck Toggle"
scoreboard objectives add hp_regen_delay dummy "HP Regen Delay"
scoreboard objectives add cd_spell dummy "Spell Cooldown"
scoreboard objectives add cd_spell_fire dummy "Fire Spell Cooldown"
scoreboard objectives add cd_spell_ice dummy "Ice Spell Cooldown"
scoreboard objectives add cd_spell_poison dummy "Poison Spell Cooldown"
scoreboard objectives add cd_warrior_switch_throw dummy "Switch Throw Cooldown"
scoreboard objectives add cd_warrior_tenacity_charge dummy "Tenacity Charge Cooldown"
scoreboard objectives add cd_warrior_third_hit dummy "Warrior Third Hit Cooldown"
scoreboard objectives add cd_ninja_multi_jump dummy "Multi Jump Cooldown"
scoreboard objectives add cd_ninja_dagger_throw dummy "Dagger Throw Cooldown"
scoreboard objectives add cd_ninja_strikethrough dummy "Strikethrough Cooldown"
scoreboard objectives add cd_ninja_smoke_bomb dummy "Smoke Bomb Cooldown"
scoreboard objectives add cd_witch_necromancy dummy "Necromancy Cooldown"
scoreboard objectives add cd_witch_staff_mastery dummy "Staff Mastery Cooldown"
scoreboard objectives add cd_archer_chain_lightning dummy "Chain Lightning Cooldown"
scoreboard objectives add cd_archer_crit_focus dummy "Crit Focus Cooldown"
scoreboard objectives add cd_archer_knockback_boost dummy "Levitate Cooldown"
scoreboard objectives add cd_tank_slam dummy "Shield Slam Cooldown"
scoreboard objectives add cd_tank_fortify dummy "Fortify Cooldown"
scoreboard objectives add cd_tank_taunt dummy "Taunt Cooldown"
scoreboard objectives add cd_weapon_witch_staff dummy "Staff Cooldown"
scoreboard objectives add warrior_third_hit dummy "Warrior Third Hit"
scoreboard objectives add tenacity_strike dummy "Tenacity Strike"
scoreboard objectives add ninja_air_jumps dummy "Ninja Air Jumps"
scoreboard objectives add rebirth_count dummy "Rebirth Count"
execute as @a[tag=!mwr_initialized] run function setup/player_init
