scoreboard players set @s class_primary 0
scoreboard players set @s class_request 0
scoreboard players set @s class_confirmed 0
scoreboard players set @s subclass_primary 0
scoreboard players set @s subclass_request 0
scoreboard players set @s subclass_confirmed 0
scoreboard players set @s fx_color 0
scoreboard players set @s ability_toggle_1 0
scoreboard players set @s ability_toggle_2 0
scoreboard players set @s ability_toggle_3 0
scoreboard players set @s ability_toggle_4 0
scoreboard players set @s ability_toggle_5 0
scoreboard players set @s xp_total 0
scoreboard players set @s xp_spent 0
scoreboard players set @s xp_available 0
scoreboard players set @s xp_tree_state 0
scoreboard players set @s morph_state 0
scoreboard players set @s morph_request 0
scoreboard players set @s plasma 100
scoreboard players set @s plasma_max 100
scoreboard players set @s plasma_drain 0
scoreboard players set @s cd_class 0
scoreboard players set @s cd_ability_1 0
scoreboard players set @s cd_ability_2 0
scoreboard players set @s cd_ability_3 0
scoreboard players set @s cd_ability_4 0
scoreboard players set @s cd_ability_5 0
scoreboard players set @s cd_morph 0
scoreboard players set @s water_exit 0
scoreboard players set @s lycan_vitality 0
scoreboard players set @s ww_bonus_hp 0
scoreboard players set @s morph_bonus 0
scoreboard players set @s skill_vampire_bite 0
scoreboard players set @s skill_blood_thirst 0
scoreboard players set @s skill_midnight_strength 0
scoreboard players set @s skill_bat_morph 0
scoreboard players set @s skill_summon_vampire_troops 0
scoreboard players set @s skill_vampire_compel 0
scoreboard players set @s skill_wolf_bite 0
scoreboard players set @s skill_werewolf_roar 0
scoreboard players set @s skill_shadow_wolf_morph 0
scoreboard players set @s skill_werewolf_scent 0
scoreboard players set @s skill_banshee_invisibility 0
scoreboard players set @s skill_sonic_scream 0
scoreboard players set @s skill_banshee_phase 0
scoreboard players set @s skill_banshee_morph 0
scoreboard players set @s banshee_mind_fracture 0
scoreboard players set @s banshee_mind_fracture_enabled 0
scoreboard players set @s skill_banshee_soul 0
scoreboard players set @s banshee_soul_active 0
scoreboard players set @s skill_switch_throw 0
scoreboard players set @s skill_tenacity_charge 0
scoreboard players set @s skill_third_hit_double 0
scoreboard players set @s skill_ninja_agility 0
scoreboard players set @s skill_multi_jump 0
scoreboard players set @s skill_dagger_throw 0
scoreboard players set @s skill_strikethrough 0
scoreboard players set @s skill_smoke_bomb 0
scoreboard players set @s skill_spell_mastery 0
scoreboard players set @s skill_necromancy 0
scoreboard players set @s skill_staff_mastery 0
scoreboard players set @s skill_chain_lightning 0
scoreboard players set @s skill_crit_focus 0
scoreboard players set @s skill_levitate 0
scoreboard players set @s skill_knockback_boost 0
scoreboard players set @s skill_explosive_arrows 0
scoreboard players set @s skill_shield_slam 0
scoreboard players set @s skill_fortify 0
scoreboard players set @s skill_taunt 0
scoreboard players set @s skill_public_vitality 0
scoreboard players set @s skill_public_haste 0
scoreboard players set @s skill_public_parkours 0
scoreboard players set @s skill_public_second_life 0
scoreboard players set @s skill_public_adrenaline 0
scoreboard players set @s skill_public_hp_regen 0
scoreboard players set @s skill_public_xp_boost 0
scoreboard players set @s skill_public_luck 0
scoreboard players set @s parkourist_active 0
scoreboard players set @s adrenaline_active 0
scoreboard players set @s midnight_strength_active 0
scoreboard players set @s werewolf_scent_active 0
scoreboard players set @s scent_toggle_state 0
scoreboard players set @s scent_toggle_initialized 0
scoreboard players set @s banshee_phase_active 0
scoreboard players set @s fall_immunity_active 0
scoreboard players set @s public_parkourist_enabled 1
scoreboard players set @s public_hp_regen_enabled 1
scoreboard players set @s public_xp_boost_enabled 1
scoreboard players set @s public_skill_toggles_ready 1
scoreboard players set @s skill_toggles_ready 0
scoreboard players set @s second_life_cd 0
scoreboard players set @s skill_vampire_bite_enabled 0
scoreboard players set @s skill_midnight_strength_enabled 0
scoreboard players set @s skill_summon_vampire_troops_enabled 0
scoreboard players set @s skill_vampire_compel_enabled 0
scoreboard players set @s skill_wolf_bite_enabled 0
scoreboard players set @s skill_werewolf_roar_enabled 0
scoreboard players set @s lycan_vitality_enabled 0
scoreboard players set @s skill_sonic_scream_enabled 0
scoreboard players set @s skill_banshee_invisibility_enabled 0
scoreboard players set @s skill_banshee_phase_enabled 0
scoreboard players set @s skill_banshee_soul_enabled 0
scoreboard players set @s skill_switch_throw_enabled 0
scoreboard players set @s skill_tenacity_charge_enabled 0
scoreboard players set @s skill_third_hit_double_enabled 0
scoreboard players set @s skill_ninja_agility_enabled 0
scoreboard players set @s skill_multi_jump_enabled 0
scoreboard players set @s skill_dagger_throw_enabled 0
scoreboard players set @s skill_strikethrough_enabled 0
scoreboard players set @s skill_smoke_bomb_enabled 0
scoreboard players set @s skill_necromancy_enabled 0
scoreboard players set @s skill_chain_lightning_enabled 0
scoreboard players set @s skill_crit_focus_enabled 0
scoreboard players set @s skill_levitate_enabled 0
scoreboard players set @s skill_shield_slam_enabled 0
scoreboard players set @s skill_fortify_enabled 0
scoreboard players set @s skill_taunt_enabled 0
scoreboard players set @s skill_public_luck_enabled 0
scoreboard players set @s hp_regen_delay 0
scoreboard players set @s cd_spell 0
scoreboard players set @s cd_spell_fire 0
scoreboard players set @s cd_spell_ice 0
scoreboard players set @s cd_spell_poison 0
scoreboard players set @s cd_warrior_switch_throw 0
scoreboard players set @s cd_warrior_tenacity_charge 0
scoreboard players set @s cd_warrior_third_hit 0
scoreboard players set @s cd_ninja_multi_jump 0
scoreboard players set @s cd_ninja_dagger_throw 0
scoreboard players set @s cd_ninja_strikethrough 0
scoreboard players set @s cd_ninja_smoke_bomb 0
scoreboard players set @s cd_witch_necromancy 0
scoreboard players set @s cd_witch_staff_mastery 0
scoreboard players set @s cd_archer_chain_lightning 0
scoreboard players set @s cd_archer_crit_focus 0
scoreboard players set @s cd_archer_knockback_boost 0
scoreboard players set @s cd_tank_slam 0
scoreboard players set @s cd_tank_fortify 0
scoreboard players set @s cd_tank_taunt 0
scoreboard players set @s cd_weapon_witch_staff 0
scoreboard players set @s warrior_third_hit 0
scoreboard players set @s tenacity_strike 0
scoreboard players set @s ninja_air_jumps 0
scoreboard players set @s rebirth_count 0
tag @s add mwr_initialized
